site_name: Past1000 API Documentation
site_description: Comprehensive API documentation for the Past1000 climate reconstruction analysis library
site_author: SongshGeo
site_url: https://songshgeo.github.io/past1000

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

repo_name: SongshGeo/past1000
repo_url: https://github.com/SongshGeo/past1000

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - API Reference:
    - Core Modules:
      - Data Processing: api/data.md
      - Historical Records: api/historical-records.md
      - Filters: api/filters.md
      - Process: api/process.md
    - Analysis Modules:
      - Comparison: api/compare.md
      - Calibration: api/calibration.md
      - Monte Carlo: api/mc.md
    - Agent-Based Model:
      - ABM Overview: api/abm.md
      - Climate Observer: api/climate-observer.md
    - Utilities:
      - Constants: api/constants.md
      - Utils: api/utils.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Advanced Analysis: examples/advanced-analysis.md
    - ABM Simulation: examples/abm-simulation.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Changelog: development/changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SongshGeo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/songshgeo
  version:
    provider: mike
