# 项目根目录
root: /Users/songshgeo/Documents/VSCode/past1000
# 项目数据目录
processed: ${ds.root}/data
multirun: ${ds.root}/multirun

# 数据目录
cmip6: /Volumes/CMIP6/past1000
# 其它数据文件夹
data: /Users/songshgeo/Documents/Datasets
# 重建数据
noaa: ${ds.data}/东亚古气候重建数据

base_maps:
  china: ${ds.data}/中国标准地图-审图号GS(2020)4619号-shp格式/国界线.shp
  yrb: ${ds.data}/黄河流域矢量图/空间范围/huang_huai_hai.shp

# 千年旱涝地图集数据
atlas:
  file: ${ds.data}/中国历史千年旱涝数据/中国千年区域极端旱涝地图集（表格） - 杨煜达 主编.xlsx
  shp: ${ds.data}/中国历史千年旱涝数据/point.shp
  region: 华北地区

spei:
  folder: ${ds.data}/黄河流域SPEI干旱指数
  pet: ${ds.spei.folder}/month_pet_0.1degree.nc
  pr: ${ds.spei.folder}/month_pre_0.1degree.nc
  pattern: ${ds.spei.folder}/spei_penman/spei_spei_{dist}_{freq}.nc

# abm: ${ds.multirun}/2025-07-27/23-18-33  # 之前的
abm: ${ds.multirun}/2025-09-11/15-03-59

# 整合校验数据，提取夏季降水，并保存为nc文件
instrumental:
  input: ${ds.data}/中国1900以来逐月降水
  output: ${ds.processed}/JAS_precipitation_1900-2017.nc
  agg_months:
    - 7
    - 8
    - 9
  agg_method: sum

includes:
- "chen2020f"  # not good
- "li2015b"  # not good
- "li2019a"  # not good
- "liu2020"  # not good
- "shi2017"
- "shi2018"
- "tan2011"  # not good
- "xu2023c"  # great
- "yang2016"  # great
# - "yang2019d"  # terrible
- "yi2010"  # very good
- "yi2012"  # very good

out:
  tree_ring: ${ds.processed}/combined_mean.csv
  precip_z: ${ds.processed}/summer_precip_z.csv
  sites_corr: ${ds.processed}/sites_corr.csv
  tree_ring_uncertainty: ${ds.processed}/combined_uncertainty.csv
