# 根目录
root: /Users/songshgeo/Documents/VSCode/past1000

# 数据目录
folder: /Volumes/CMIP6/past1000

# 黄河流域矢量图
shp: /Users/songshgeo/Documents/Datasets/黄河流域矢量图/空间范围/huang_huai_hai_merged.shp

# 千年旱涝地图集数据
atlas: "/Users/songshgeo/Documents/Datasets/中国历史千年旱涝数据/中国千年区域极端旱涝地图集（表格） - 杨煜达 主编.xlsx"
