# 项目根目录
root: /Users/songshgeo/Documents/VSCode/past1000
# 项目数据目录
processed: ${ds.root}/data
multirun: ${ds.root}/multirun

# 数据目录
cmip6: /Volumes/CMIP6/past1000
# 其它数据文件夹
data: /Users/songshgeo/Documents/Datasets
# 重建数据
noaa: ${ds.data}/东亚古气候重建数据

# 千年旱涝地图集数据
atlas:
  file: ${ds.data}/中国历史千年旱涝数据/中国千年区域极端旱涝地图集（表格） - 杨煜达 主编.xlsx
  shp: ${ds.data}/中国历史千年旱涝数据/point.shp
  region: 华北地区

spei:
  folder: ${ds.data}/黄河流域SPEI干旱指数
  pet: ${ds.spei.folder}/month_pet_0.1degree.nc
  pr: ${ds.spei.folder}/month_pre_0.1degree.nc
  pattern: ${ds.spei.folder}/spei_penman/spei_spei_{dist}_{freq}.nc

abm: ${ds.multirun}/2025-07-27/23-18-33

instrumental:
  input: ${ds.data}/中国1900以来逐月降水
  output: ${ds.processed}/JAS_precipitation_1900-2017.nc
  agg_months:
    - 7
    - 8
    - 9
  agg_method: sum


includes:
  - "hexi2019scpdsi"
  - "qinling2016precip"
  - "shanxi2015precip"
  - "tan2011precip-noaa"
  - "xu2023-asm"
  # - "yellow2019flow"
  # - "yellow2020flow"
  - "north-china-precip2010"
  - "north-china-temp-precip2011"
