# 将原始数据进行处理，并保存到本地
name: "数据预处理"

# CMIP6 数据存储的子目录模式
subdir_pattern: "{freq}/{model}"

# 输出目录：根目录下的 data 文件夹
output: "${ds.root}/data"

# 裁剪范围：黄河流域矢量图
shp: ${ds.data}/黄河流域矢量图/空间范围/huai_hai.shp  # 仅仅裁剪黄河下游
# shp: ${ds.data}/黄河流域矢量图/空间范围/huang_huai_hai_merged.shp  # 裁剪黄河全流域

# 自然重建数据
recon:
  # 降水
  shi2018:
    path: ${ds.noaa}/shi2018/RAP_v1.nc
    type: grid
    process:
      open_dataarray:
        decode_times: False
      clip_data:

        shp: ${how.shp}
      convert_time_axis:
        begin_year: 1470
    out: ${how.output}/recon/shi2018.nc
    variable: 'pr'
