defaults:
- ds: mac
- how: process
- override hydra/job_logging: log
- _self_


# # 历史记录数据的时间段
# START = 1000
# STAGE1 = 1469
# STAGE2 = 1659
# END = 1900
# FINAL = 2010
years:
  start: 1000
  stage1: 1469
  stage2: 1659
  end: 1900
  final: 2010

# Testing mode - when enabled, only test logging and exit
# 测试模式 - 当启用时，仅测试日志并退出
test_mode: false

# 是否重新计算数据，如果为true，则重新计算数据，否则使用本地保存的中间变量数据
# 中间变量数据的路径为 {ds.processed}/*.csv
# 可以在 ds/mac.yaml 中配置需要重新计算的数据
# 如果需要重新计算数据，则将 recalculate_data 设置为 true
recalculate_data: false

# 相关性计算方法
corr_method: kendall
# 相关性计算侧
filter_side: right

agg_method: mean
to_int: true
resolution: 0.5
to_std: sampling

low_pass:
  window_size: 30
  method: rolling_mean  # rolling_mean, gaussian, butterworth
  center: true
