defaults:
- ds: pure
- how: process
- model: exp
- override hydra/job_logging: log
- _self_

# Testing mode - when enabled, only test logging and exit
# 测试模式 - 当启用时，仅测试日志并退出
test_mode: false

# 是否重新计算数据，如果为true，则重新计算数据，否则使用本地保存的中间变量数据
# 中间变量数据的路径为 {ds.processed}/*.csv
# 可以在 ds/mac.yaml 中配置需要重新计算的数据
# 如果需要重新计算数据，则将 recalculate_data 设置为 true
recalculate_data: false

# 相关性计算方法
corr_method: kendall
# 相关性计算侧
filter_side: right

agg_method: mean
to_int: true
resolution: 0.5
to_std: sampling
# 在相关性计算时，控制默认的最小样本数，至少为 3，但 5+ 计算 std 更合理
min_period: 10
# 前百分之 % 的最大值区间
ratio: 0.05

low_pass:
  window_size: 30
  method: rolling_mean  # rolling_mean, gaussian, butterworth
  center: true

# 使用指定的校验数据
using_val_data: 'china'  # china, gpcc, cru

violin_windows:
- 20
- 40
- 60
