# config/hydra/job_logging/custom.yaml
# @package hydra.job_logging
version: 1
formatters:
  simple:
    format: "%(levelname)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO          # 从 WARNING 改为 INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG         # 保持 DEBUG
    formatter: simple
    filename: ${hydra:runtime.output_dir}/app.log
    encoding: utf-8
root:
  level: DEBUG           # 保持 DEBUG，确保 DEBUG 能写入文件
  handlers: [console, file]
disable_existing_loggers: false
